import os
import io
import wave
import json
import logging
import numpy as np
from scipy import signal
from fastapi import FastAPI, HTTPException, Response, status
from pydantic import BaseModel, Field
from typing import List, Optional
from groq import Groq
from dotenv import load_dotenv
import httpx 

load_dotenv()

# --- Configuration ---
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
DEEPGRAM_API_KEY = os.environ.get("DEEPGRAM_TTS") 

LLM_MODEL_ID = "llama-3.1-8b-instant"
TTS_MODEL_ID = "aura-2-thalia-en" 
SAMPLE_RATE_REQUIRED = 16000
LOG_LEVEL = logging.INFO

logging.basicConfig(level=LOG_LEVEL, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("hicapy")

app = FastAPI(title="hicapy/Text Microservice")

# --- Initialize Clients ---
try:
    if not GROQ_API_KEY:
        logger.warning("GROQ_API_KEY not found. Text generation will fail.")
    client = Groq(api_key=GROQ_API_KEY)
except Exception as e:
    logger.error(f"Failed to initialize Groq Client: {e}")
    raise

# --- Data Models ---
class GenerateTextRequest(BaseModel):
    bot_id: str
    system_prompt: str
    summary_memory: Optional[str] = ""
    recent_messages: List[str] = []
    user_message: str

class GenerateTextResponse(BaseModel):
    bot_id: str
    response_text: str
    should_speak: bool
    confidence: float = 0.0
    reason: Optional[str] = None

class GenerateAudioRequest(BaseModel):
    bot_id: str
    system_prompt: str
    summary_memory: Optional[str] = ""
    recent_messages: List[str] = []
    user_message: str
    voice: str = "default"
    force_tts: bool = False

# --- Helper Functions ---
class AudioProcessor:
    @staticmethod
    def process_wav_bytes(input_wav_bytes: bytes, target_rate: int = 16000) -> bytes:
        try:
            with wave.open(io.BytesIO(input_wav_bytes), 'rb') as source_wav:
                original_rate = source_wav.getframerate()
                channels = source_wav.getnchannels()
                width = source_wav.getsampwidth()
                n_frames = source_wav.getnframes()
                raw_data = source_wav.readframes(n_frames)

            if width == 2:
                dtype = np.int16
            elif width == 1:
                dtype = np.int8
            else:
                dtype = np.int16
            
            audio_data = np.frombuffer(raw_data, dtype=dtype)

            if channels == 2:
                audio_data = audio_data.reshape(-1, 2)
                audio_data = audio_data.mean(axis=1).astype(np.int16)
            
            if original_rate != target_rate:
                num_samples = int(len(audio_data) * target_rate / original_rate)
                audio_data = signal.resample(audio_data, num_samples).astype(np.int16)

            output_io = io.BytesIO()
            with wave.open(output_io, 'wb') as out_wav:
                out_wav.setnchannels(1)
                out_wav.setsampwidth(2)
                out_wav.setframerate(target_rate)
                out_wav.writeframes(audio_data.tobytes())
            
            return output_io.getvalue()

        except Exception as e:
            logger.error(f"Audio processing failed: {e}")
            raise HTTPException(status_code=500, detail=f"Audio processing error: {str(e)}")

# --- Endpoints ---

@app.post("/generate-text", response_model=GenerateTextResponse)
async def generate_text(request: GenerateTextRequest):
    try:
        messages = [
            {"role": "system", "content": request.system_prompt + "\n\n" + 
             "CRITICAL INSTRUCTION: You MUST return a valid JSON object. " +
             "Do not include markdown formatting like ```json ... ```. " +
             "Format: {\"response_text\": \"...\", \"should_speak\": boolean, \"confidence\": float, \"reason\": \"...\"}"},
            {"role": "user", "content": f"Context Summary: {request.summary_memory}\n" +
                                        f"Recent Chat History: {request.recent_messages}\n" +
                                        f"Current User Input: {request.user_message}"}
        ]

        completion = client.chat.completions.create(
            model=LLM_MODEL_ID,
            messages=messages,
            temperature=0.7,
            response_format={"type": "json_object"}
        )

        content = completion.choices[0].message.content
        logger.info(f"LLM Raw Response: {content}")
        
        decision_data = json.loads(content)

        return GenerateTextResponse(
            bot_id=request.bot_id,
            response_text=decision_data.get("response_text", ""),
            should_speak=decision_data.get("should_speak", False),
            confidence=decision_data.get("confidence", 0.0),
            reason=decision_data.get("reason", "Generated by Groq")
        )

    except json.JSONDecodeError:
        logger.error("Failed to parse LLM JSON response")
        return GenerateTextResponse(
            bot_id=request.bot_id,
            response_text="I encountered an error processing that.",
            should_speak=True,
            confidence=0.0,
            reason="JSON Parse Error"
        )
    except Exception as e:
        logger.error(f"Generate text error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/generate-audio")
async def generate_audio(request: GenerateAudioRequest):
    """
    Generates WAV audio (binary) and returns readable text in X-Transcript header.
    """
    try:
        # Step A: Get Text
        text_to_speak = ""
        should_speak = False

        if request.force_tts:
            should_speak = True
            text_resp = await generate_text(GenerateTextRequest(
                bot_id=request.bot_id, system_prompt=request.system_prompt,
                summary_memory=request.summary_memory, recent_messages=request.recent_messages,
                user_message=request.user_message
            ))
            text_to_speak = text_resp.response_text
        else:
            text_resp = await generate_text(GenerateTextRequest(
                bot_id=request.bot_id, system_prompt=request.system_prompt,
                summary_memory=request.summary_memory, recent_messages=request.recent_messages,
                user_message=request.user_message
            ))
            should_speak = text_resp.should_speak
            text_to_speak = text_resp.response_text

        if not should_speak and not request.force_tts:
            return Response(status_code=status.HTTP_204_NO_CONTENT)

        logger.info(f"Generating audio for: '{text_to_speak[:30]}...'")

        # Step B: Direct API Call
        deepgram_url = f"https://api.deepgram.com/v1/speak?model={TTS_MODEL_ID}&encoding=linear16&container=wav&sample_rate={SAMPLE_RATE_REQUIRED}"
        
        headers = {
            "Authorization": f"Token {DEEPGRAM_API_KEY}",
            "Content-Type": "application/json"
        }
        
        payload = {"text": text_to_speak}

        async with httpx.AsyncClient() as http_client:
            api_response = await http_client.post(deepgram_url, headers=headers, json=payload)
            
            if api_response.status_code != 200:
                error_detail = api_response.text
                logger.error(f"Deepgram API Error: {api_response.status_code} - {error_detail}")
                raise HTTPException(status_code=500, detail=f"Deepgram TTS Error: {error_detail}")
            
            raw_wav_content = api_response.content

        # Step C: Process Audio
        processed_wav = AudioProcessor.process_wav_bytes(raw_wav_content, SAMPLE_RATE_REQUIRED)

        # Step D: Sanitize Text for Headers
        # Headers cannot contain newlines (\n or \r). We replace them with spaces.
        # We do NOT use url-encoding, so spaces stay as spaces.
        safe_transcript = text_to_speak.replace('\n', ' ').replace('\r', '')

        # Ensure characters are latin-1 compatible (Standard HTTP limitation)
        # If text contains emojis/complex unicode, we strip/replace them to prevent server errors.
        try:
            safe_transcript.encode('latin-1')
        except UnicodeEncodeError:
            # Fallback: simple ascii approximation if strict latin-1 fails
            safe_transcript = safe_transcript.encode('ascii', 'ignore').decode('ascii')

        return Response(
            content=processed_wav,
            media_type="audio/wav",
            headers={
                "Content-Length": str(len(processed_wav)),
                "X-Bot-ID": request.bot_id,
                "Content-Disposition": 'attachment; filename="output.wav"',
                "X-Transcript": safe_transcript  # <--- Plain readable text here
            }
        )

    except Exception as e:
        logger.error(f"Generate audio error: {e}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))